### ISSUE TITLE
Assignemnt 7- Review of R package {purrr}

### ISSUE THREAD

**Issue by CristianSwift** [CristianSwift/assignment-7#1]
In this repo within the README.md I have a review of the R package purrr. Within the review I give some basic descriptions of the package including where to find it and where examples of how the package is used are located. I also share some of my opinions of the package.

2. I am OK with Mark posting my review to the course website but please do not use my name (i.e., make it anonymous).

**Comment by mdscheuerell** [comment]
Thanks, Cristian. This is definitely a package I need to spend some more time exploring.
